cp app.js ~/Sites/TennisClub/newtennis/js/
cp coachingvouchers.js ~/Sites/TennisClub/newtennis/js/
cp coachlist.js ~/Sites/TennisClub/newtennis/js/
cp dateval.js ~/Sites/TennisClub/newtennis/js/
cp documents.js ~/Sites/TennisClub/newtennis/js/
cp editnews.js ~/Sites/TennisClub/newtennis/js/
cp eventlist.js ~/Sites/TennisClub/newtennis/js/
cp faq.js ~/Sites/TennisClub/newtennis/js/
cp fetchJSONtest.js ~/Sites/TennisClub/newtennis/js/
cp gettournament.js ~/Sites/TennisClub/newtennis/js/
cp index.js ~/Sites/TennisClub/newtennis/js/
cp jquery.collapsible.js ~/Sites/TennisClub/newtennis/js/
cp jsontest.js ~/Sites/TennisClub/newtennis/js/
cp jsontest2.js ~/Sites/TennisClub/newtennis/js/
cp jsontest3.js ~/Sites/TennisClub/newtennis/js/
cp mycoaching.js ~/Sites/TennisClub/newtennis/js/
cp querystring.js ~/Sites/TennisClub/newtennis/js/
cp results.js ~/Sites/TennisClub/newtennis/js/
cp search.js ~/Sites/TennisClub/newtennis/js/
cp swag.js ~/Sites/TennisClub/newtennis/js/
cp swag.min.js ~/Sites/TennisClub/newtennis/js/
cp templates.js ~/Sites/TennisClub/newtennis/js/
cp test-orbit.js ~/Sites/TennisClub/newtennis/js/
cp testquerystring.js ~/Sites/TennisClub/newtennis/js/
cp tournaments.js ~/Sites/TennisClub/newtennis/js/
cp twitterfeed-original.js ~/Sites/TennisClub/newtennis/js/
cp twitterfeed.js ~/Sites/TennisClub/newtennis/js/
cp wordpress.js ~/Sites/TennisClub/newtennis/js/
cp app.js ~/Sites/TennisClub/newtennis/js/
cp coachingvouchers.js ~/Sites/TennisClub/newtennis/js/
cp coachlist.js ~/Sites/TennisClub/newtennis/js/
cp dateval.js ~/Sites/TennisClub/newtennis/js/
cp documents.js ~/Sites/TennisClub/newtennis/js/
cp editnews.js ~/Sites/TennisClub/newtennis/js/
cp eventlist.js ~/Sites/TennisClub/newtennis/js/
cp faq.js ~/Sites/TennisClub/newtennis/js/
cp fetchJSONtest.js ~/Sites/TennisClub/newtennis/js/
cp gettournament.js ~/Sites/TennisClub/newtennis/js/
cp index.js ~/Sites/TennisClub/newtennis/js/
cp jquery.collapsible.js ~/Sites/TennisClub/newtennis/js/
cp jsontest.js ~/Sites/TennisClub/newtennis/js/
cp jsontest2.js ~/Sites/TennisClub/newtennis/js/
cp jsontest3.js ~/Sites/TennisClub/newtennis/js/
cp mycoaching.js ~/Sites/TennisClub/newtennis/js/
cp querystring.js ~/Sites/TennisClub/newtennis/js/
cp results.js ~/Sites/TennisClub/newtennis/js/
cp search.js ~/Sites/TennisClub/newtennis/js/
cp swag.js ~/Sites/TennisClub/newtennis/js/
cp swag.min.js ~/Sites/TennisClub/newtennis/js/
cp templates.js ~/Sites/TennisClub/newtennis/js/
cp test-orbit.js ~/Sites/TennisClub/newtennis/js/
cp testquerystring.js ~/Sites/TennisClub/newtennis/js/
cp tournaments.js ~/Sites/TennisClub/newtennis/js/
cp twitterfeed-original.js ~/Sites/TennisClub/newtennis/js/
cp twitterfeed.js ~/Sites/TennisClub/newtennis/js/
cp wordpress.js ~/Sites/TennisClub/newtennis/js/
cp app.js ~/Sites/TennisClub/newtennis/js/
cp coachingvouchers.js ~/Sites/TennisClub/newtennis/js/
cp coachlist.js ~/Sites/TennisClub/newtennis/js/
cp dateval.js ~/Sites/TennisClub/newtennis/js/
cp documents.js ~/Sites/TennisClub/newtennis/js/
cp editnews.js ~/Sites/TennisClub/newtennis/js/
cp eventlist.js ~/Sites/TennisClub/newtennis/js/
cp faq.js ~/Sites/TennisClub/newtennis/js/
cp fetchJSONtest.js ~/Sites/TennisClub/newtennis/js/
cp gettournament.js ~/Sites/TennisClub/newtennis/js/
cp index.js ~/Sites/TennisClub/newtennis/js/
cp jquery.collapsible.js ~/Sites/TennisClub/newtennis/js/
cp jsontest.js ~/Sites/TennisClub/newtennis/js/
cp jsontest2.js ~/Sites/TennisClub/newtennis/js/
cp jsontest3.js ~/Sites/TennisClub/newtennis/js/
cp mycoaching.js ~/Sites/TennisClub/newtennis/js/
cp querystring.js ~/Sites/TennisClub/newtennis/js/
cp results.js ~/Sites/TennisClub/newtennis/js/
cp search.js ~/Sites/TennisClub/newtennis/js/
cp swag.js ~/Sites/TennisClub/newtennis/js/
cp swag.min.js ~/Sites/TennisClub/newtennis/js/
cp templates.js ~/Sites/TennisClub/newtennis/js/
cp test-orbit.js ~/Sites/TennisClub/newtennis/js/
cp testquerystring.js ~/Sites/TennisClub/newtennis/js/
cp tournaments.js ~/Sites/TennisClub/newtennis/js/
cp twitterfeed-original.js ~/Sites/TennisClub/newtennis/js/
cp twitterfeed.js ~/Sites/TennisClub/newtennis/js/
cp wordpress.js ~/Sites/TennisClub/newtennis/js/
cp app.js ~/Sites/TennisClub/newtennis/js/
cp coachingvouchers.js ~/Sites/TennisClub/newtennis/js/
cp coachlist.js ~/Sites/TennisClub/newtennis/js/
cp dateval.js ~/Sites/TennisClub/newtennis/js/
cp documents.js ~/Sites/TennisClub/newtennis/js/
cp editnews.js ~/Sites/TennisClub/newtennis/js/
cp eventlist.js ~/Sites/TennisClub/newtennis/js/
cp faq.js ~/Sites/TennisClub/newtennis/js/
cp fetchJSONtest.js ~/Sites/TennisClub/newtennis/js/
cp gettournament.js ~/Sites/TennisClub/newtennis/js/
cp index.js ~/Sites/TennisClub/newtennis/js/
cp jquery.collapsible.js ~/Sites/TennisClub/newtennis/js/
cp jsontest.js ~/Sites/TennisClub/newtennis/js/
cp jsontest2.js ~/Sites/TennisClub/newtennis/js/
cp jsontest3.js ~/Sites/TennisClub/newtennis/js/
cp mycoaching.js ~/Sites/TennisClub/newtennis/js/
cp querystring.js ~/Sites/TennisClub/newtennis/js/
cp results.js ~/Sites/TennisClub/newtennis/js/
cp search.js ~/Sites/TennisClub/newtennis/js/
cp swag.js ~/Sites/TennisClub/newtennis/js/
cp swag.min.js ~/Sites/TennisClub/newtennis/js/
cp templates.js ~/Sites/TennisClub/newtennis/js/
cp test-orbit.js ~/Sites/TennisClub/newtennis/js/
cp testquerystring.js ~/Sites/TennisClub/newtennis/js/
cp tournaments.js ~/Sites/TennisClub/newtennis/js/
cp twitterfeed-original.js ~/Sites/TennisClub/newtennis/js/
cp twitterfeed.js ~/Sites/TennisClub/newtennis/js/
cp wordpress.js ~/Sites/TennisClub/newtennis/js/
